# Dependencies
# markdown:         redcarpet
markdown:         kramdown
highlighter:      pygments


# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Poorna Talkad Sukumar
# tagline:          ''
description:      ''
url:              https://poornats.github.io
baseurl:          /

author:
  name:           ''
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poornats/poornats.github.io
